name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: ["master"]
    paths:
      - .github/workflows/semgrep.yml
jobs:
  semgrep:
    name: semgrep ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_REPO_NAME: ${{ github.repository }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --output scan_results.json --json
